//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cibertec.MegaMarket.BL.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public int IdDistrito { get; set; }
        public int IdPais { get; set; }
        public int IdCiudad { get; set; }
        public string Nombre { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
